// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// [FirebaseOptions] do ambiente de **develop** (projeto `debugaomascote-dev`).
/// Classe renomeada de `DefaultFirebaseOptions` (gerada pelo FlutterFire) para
/// `DevFirebaseOptions`, evitando colisão com `firebase_options.dart` (prod) —
/// os dois são importados juntos pelo seletor `lib/core/firebase_env.dart`.
/// Escolhido em build-time via `--dart-define=APP_ENV=dev` (ver `firebase_env.dart`).
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7QiJCKiQcRV8xRgDrUbz-MV3grz5d73A',
    appId: '1:1040054035723:web:3b999fd0a97a0a2f246e0e',
    messagingSenderId: '1040054035723',
    projectId: 'debugaomascote-dev',
    authDomain: 'debugaomascote-dev.firebaseapp.com',
    storageBucket: 'debugaomascote-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzZ01r8DirGdRHsa3LBzU0fOSVADDz1qU',
    appId: '1:1040054035723:android:8362d0f2f55d7ed3246e0e',
    messagingSenderId: '1040054035723',
    projectId: 'debugaomascote-dev',
    storageBucket: 'debugaomascote-dev.firebasestorage.app',
  );
}
