// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvVaLiGICvp6Uyi0rW0KqTBIM7R5sWT-A',
    appId: '1:823859588989:web:d29bdad072f04ae4b56614',
    messagingSenderId: '823859588989',
    projectId: 'debugaomascote',
    authDomain: 'debugaomascote.firebaseapp.com',
    storageBucket: 'debugaomascote.firebasestorage.app',
    measurementId: 'G-XDJ5V9GVQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmaGxbr_BzlGfzav1uxr3YlTDDYZSPi_c',
    appId: '1:823859588989:android:1599d544e0590e2cb56614',
    messagingSenderId: '823859588989',
    projectId: 'debugaomascote',
    storageBucket: 'debugaomascote.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKP_gFedY9L8BbeoICsKyAU9USC8eMPe4',
    appId: '1:823859588989:ios:f0fbd113a98f3ed9b56614',
    messagingSenderId: '823859588989',
    projectId: 'debugaomascote',
    storageBucket: 'debugaomascote.firebasestorage.app',
    androidClientId: '823859588989-b2idfu82dr00p3qlbp7op6vrr6cdri5d.apps.googleusercontent.com',
    iosClientId: '823859588989-id8d3221aim3gaq2mijikmvriisisi49.apps.googleusercontent.com',
    iosBundleId: 'com.example.debugaOMascote',
  );
}
